# Generated by Django 4.2.4 on 2023-09-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='for_user',
            field=models.CharField(default=100, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='prod_code',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Facilis quae nemo ducimus, aperiam reprehenderit sit provident quam, enim tempore ea eligendi vel facere? In numquam deleniti, debitis quod odit tenetur.', max_length=300),
        ),
    ]
