# Generated by Django 4.2.4 on 2023-10-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_item_for_user_item_prod_code_alter_item_item_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='for_user',
            field=models.CharField(default='xyz', max_length=100),
        ),
    ]
